export class Article {
    constructor(
        public datum: Date,
        public reportType: string,
        public type: string,
        public tin: string,
        public tinIssuedBy: string,
        public resCountryCode: string,
        public firstName: string,
        public lastName: string,
        public name: string,
        public countryCode: string,
        public street: string,
        public city: string,
        public postCode: string,
        public birthDate: Date,
        public accountNumber: string,
        public accountNumberType: string,
        public acctHolderType: string,
        public accountDescription: string,
        public accountBalanceCurrCode: string,
        public accountBalance: number,
        public accountBalanceUSD: number,
        public accountBalanceEUR: number ,
        public payment: number,
        public paymentType: string,
        public paymentCurrencyCode: string,
        public controllingPersonRead: boolean,
        public closedAccount: boolean,
        public dormantAccount: boolean,
        public taxCode: string,
        public taxCode2: string,
        public taxCode3: string,
        public resCountryCode2: string,
        public resCountryCode3: string
    ) {}
} 
